-- ========================================
-- WorkBoard: Oracle DB Table Design
-- 근태/연차 관리 시스템 데이터베이스 설계
-- ========================================

-- 1. 코드 테이블 (Code Tables)
-- ========================================

-- 1-1. 직급 코드 테이블
CREATE TABLE TB_POSITION_CODE (
  POSITION_CODE  VARCHAR2(10)  PRIMARY KEY,
  POSITION_NAME  VARCHAR2(50)  NOT NULL,
  DISPLAY_ORDER  NUMBER(3)     NOT NULL,
  USE_YN         VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
  CREATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CK_POSITION_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

INSERT INTO TB_POSITION_CODE VALUES ('L1', 'Junior', 1, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO TB_POSITION_CODE VALUES ('L2', 'Middle', 2, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO TB_POSITION_CODE VALUES ('L3', 'Senior', 3, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO TB_POSITION_CODE VALUES ('L4', 'Manager', 4, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);


-- 1-2. 부서 코드 테이블
CREATE TABLE TB_DEPARTMENT_CODE (
  DEPARTMENT_CODE  VARCHAR2(10)  PRIMARY KEY,
  DEPARTMENT_NAME  VARCHAR2(100) NOT NULL,
  DISPLAY_ORDER    NUMBER(3)     NOT NULL,
  USE_YN           VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
  CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CK_DEPT_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

INSERT INTO TB_DEPARTMENT_CODE VALUES ('DEV', '개발팀', 1, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);


-- 1-3. 연차 신청 상태 코드 테이블
CREATE TABLE TB_LEAVE_STATUS_CODE (
  LEAVE_STATUS_CODE  VARCHAR2(20)  PRIMARY KEY,
  LEAVE_STATUS_NAME  VARCHAR2(50)  NOT NULL,
  DISPLAY_ORDER      NUMBER(3)     NOT NULL,
  USE_YN             VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
  CREATED_AT         TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT         TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CK_LEAVE_STATUS_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

INSERT INTO TB_LEAVE_STATUS_CODE VALUES ('PENDING', '검토중', 1, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO TB_LEAVE_STATUS_CODE VALUES ('APPROVED', '승인', 2, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO TB_LEAVE_STATUS_CODE VALUES ('REJECTED', '반려', 3, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);


-- 1-4. 근태 상태 코드 테이블
CREATE TABLE TB_ATTENDANCE_STATUS_CODE (
  ATTENDANCE_STATUS_CODE  VARCHAR2(20)  PRIMARY KEY,
  ATTENDANCE_STATUS_NAME  VARCHAR2(50)  NOT NULL,
  DISPLAY_ORDER           NUMBER(3)     NOT NULL,
  USE_YN                  VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
  CREATED_AT              TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT              TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CK_ATTEND_STATUS_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

INSERT INTO TB_ATTENDANCE_STATUS_CODE VALUES ('PRESENT', '출근', 1, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO TB_ATTENDANCE_STATUS_CODE VALUES ('ABSENT', '결근', 2, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO TB_ATTENDANCE_STATUS_CODE VALUES ('LEAVE', '휴가', 3, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO TB_ATTENDANCE_STATUS_CODE VALUES ('HOLIDAY', '공휴일', 4, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);


-- 2. 마스터 테이블 (Master Tables)
-- ========================================

-- 2-1. 사용자 테이블
CREATE TABLE TB_USERS (
  USER_ID           VARCHAR2(50)   PRIMARY KEY,
  EMPLOYEE_NO       VARCHAR2(20)   NOT NULL UNIQUE,
  USER_NAME         VARCHAR2(100)  NOT NULL,
  DEPARTMENT_CODE   VARCHAR2(10)   NOT NULL,
  POSITION_CODE     VARCHAR2(10)   NOT NULL,
  EMAIL             VARCHAR2(100)  NOT NULL UNIQUE,
  TOTAL_LEAVE_DAYS  NUMBER(3)      DEFAULT 15 NOT NULL,
  STATUS            VARCHAR2(1)    DEFAULT 'A' NOT NULL,
  CREATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_USERS_DEPT FOREIGN KEY (DEPARTMENT_CODE) REFERENCES TB_DEPARTMENT_CODE(DEPARTMENT_CODE),
  CONSTRAINT FK_USERS_POSITION FOREIGN KEY (POSITION_CODE) REFERENCES TB_POSITION_CODE(POSITION_CODE),
  CONSTRAINT CK_USERS_STATUS CHECK (STATUS IN ('A', 'I', 'D')) -- A: Active, I: Inactive, D: Deleted
);

CREATE INDEX IDX_USERS_EMPLOYEE_NO ON TB_USERS(EMPLOYEE_NO);
CREATE INDEX IDX_USERS_EMAIL ON TB_USERS(EMAIL);
CREATE INDEX IDX_USERS_DEPT ON TB_USERS(DEPARTMENT_CODE);
CREATE INDEX IDX_USERS_POSITION ON TB_USERS(POSITION_CODE);


-- 2-2. 로그인 계정 테이블 (USERS와 1:1 관계)
CREATE TABLE TB_LOGIN_ACCOUNTS (
  LOGIN_ACCOUNT_ID  VARCHAR2(50)   PRIMARY KEY,
  USER_ID           VARCHAR2(50)   NOT NULL UNIQUE,
  EMAIL             VARCHAR2(100)  NOT NULL UNIQUE,
  PASSWORD_HASH     VARCHAR2(500)  NOT NULL,
  LAST_LOGIN_AT     TIMESTAMP,
  LOGIN_ATTEMPT_CNT NUMBER(3)      DEFAULT 0,
  LOCKED_YN         VARCHAR2(1)    DEFAULT 'N' NOT NULL,
  CREATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_LOGIN_ACCOUNTS_USER FOREIGN KEY (USER_ID) REFERENCES TB_USERS(USER_ID),
  CONSTRAINT CK_LOGIN_LOCKED_YN CHECK (LOCKED_YN IN ('Y', 'N'))
);

CREATE INDEX IDX_LOGIN_ACCOUNTS_USER ON TB_LOGIN_ACCOUNTS(USER_ID);
CREATE INDEX IDX_LOGIN_ACCOUNTS_EMAIL ON TB_LOGIN_ACCOUNTS(EMAIL);


-- 3. 거래 테이블 (Transaction Tables)
-- ========================================

-- 3-1. 연차 신청 테이블
CREATE TABLE TB_LEAVE_REQUESTS (
  LEAVE_REQUEST_ID   VARCHAR2(50)   PRIMARY KEY,
  USER_ID            VARCHAR2(50)   NOT NULL,
  START_DATE         DATE           NOT NULL,
  END_DATE           DATE           NOT NULL,
  LEAVE_REASON       VARCHAR2(500)  NOT NULL,
  LEAVE_STATUS_CODE  VARCHAR2(20)   DEFAULT 'PENDING' NOT NULL,
  APPROVAL_USER_ID   VARCHAR2(50),
  APPROVED_AT        TIMESTAMP,
  REJECTION_REASON   VARCHAR2(500),
  CREATED_AT         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_LEAVE_REQUESTS_USER FOREIGN KEY (USER_ID) REFERENCES TB_USERS(USER_ID),
  CONSTRAINT FK_LEAVE_REQUESTS_APPROVAL_USER FOREIGN KEY (APPROVAL_USER_ID) REFERENCES TB_USERS(USER_ID),
  CONSTRAINT FK_LEAVE_REQUESTS_STATUS FOREIGN KEY (LEAVE_STATUS_CODE) REFERENCES TB_LEAVE_STATUS_CODE(LEAVE_STATUS_CODE),
  CONSTRAINT CK_LEAVE_DATES CHECK (END_DATE >= START_DATE)
);

CREATE INDEX IDX_LEAVE_REQUESTS_USER ON TB_LEAVE_REQUESTS(USER_ID);
CREATE INDEX IDX_LEAVE_REQUESTS_STATUS ON TB_LEAVE_REQUESTS(LEAVE_STATUS_CODE);
CREATE INDEX IDX_LEAVE_REQUESTS_DATES ON TB_LEAVE_REQUESTS(START_DATE, END_DATE);
CREATE INDEX IDX_LEAVE_REQUESTS_APPROVAL_USER ON TB_LEAVE_REQUESTS(APPROVAL_USER_ID);


-- 3-2. 근태 기록 테이블
CREATE TABLE TB_ATTENDANCE_RECORDS (
  ATTENDANCE_RECORD_ID  VARCHAR2(50)   PRIMARY KEY,
  USER_ID              VARCHAR2(50)   NOT NULL,
  ATTENDANCE_DATE      DATE           NOT NULL,
  CHECK_IN_TIME        VARCHAR2(5),   -- HH:mm 형식
  CHECK_OUT_TIME       VARCHAR2(5),   -- HH:mm 형식
  ATTENDANCE_STATUS    VARCHAR2(20)   DEFAULT 'PRESENT' NOT NULL,
  REMARKS              VARCHAR2(500),
  CREATED_AT           TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT           TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_ATTENDANCE_USER FOREIGN KEY (USER_ID) REFERENCES TB_USERS(USER_ID),
  CONSTRAINT FK_ATTENDANCE_STATUS FOREIGN KEY (ATTENDANCE_STATUS) REFERENCES TB_ATTENDANCE_STATUS_CODE(ATTENDANCE_STATUS_CODE),
  CONSTRAINT UQ_ATTENDANCE_UNIQUE UNIQUE (USER_ID, ATTENDANCE_DATE)
);

CREATE INDEX IDX_ATTENDANCE_USER ON TB_ATTENDANCE_RECORDS(USER_ID);
CREATE INDEX IDX_ATTENDANCE_DATE ON TB_ATTENDANCE_RECORDS(ATTENDANCE_DATE);
CREATE INDEX IDX_ATTENDANCE_STATUS ON TB_ATTENDANCE_RECORDS(ATTENDANCE_STATUS);


-- 4. 뷰 (Views)
-- ========================================

-- 4-1. 사용자 연차 현황 뷰
CREATE OR REPLACE VIEW VW_USER_LEAVE_SUMMARY AS
SELECT
  U.USER_ID,
  U.EMPLOYEE_NO,
  U.USER_NAME,
  U.DEPARTMENT_CODE,
  U.POSITION_CODE,
  U.TOTAL_LEAVE_DAYS,
  NVL(SUM(CASE WHEN LR.LEAVE_STATUS_CODE = 'APPROVED'
                 THEN (LR.END_DATE - LR.START_DATE + 1)
                ELSE 0 END), 0) AS USED_LEAVE_DAYS,
  (U.TOTAL_LEAVE_DAYS - NVL(SUM(CASE WHEN LR.LEAVE_STATUS_CODE = 'APPROVED'
                                       THEN (LR.END_DATE - LR.START_DATE + 1)
                                      ELSE 0 END), 0)) AS REMAINING_LEAVE_DAYS
FROM TB_USERS U
LEFT JOIN TB_LEAVE_REQUESTS LR
  ON U.USER_ID = LR.USER_ID
  AND EXTRACT(YEAR FROM LR.START_DATE) = EXTRACT(YEAR FROM SYSDATE)
WHERE U.STATUS = 'A'
GROUP BY U.USER_ID, U.EMPLOYEE_NO, U.USER_NAME, U.DEPARTMENT_CODE,
         U.POSITION_CODE, U.TOTAL_LEAVE_DAYS;


-- 4-2. 월별 팀원 휴가 현황 뷰
CREATE OR REPLACE VIEW VW_TEAM_LEAVE_BY_DATE AS
SELECT
  LR.START_DATE + ROWNUM - 1 AS LEAVE_DATE,
  U.USER_ID,
  U.EMPLOYEE_NO,
  U.USER_NAME,
  U.DEPARTMENT_CODE,
  DC.DEPARTMENT_NAME
FROM TB_LEAVE_REQUESTS LR
JOIN TB_USERS U ON LR.USER_ID = U.USER_ID
JOIN TB_DEPARTMENT_CODE DC ON U.DEPARTMENT_CODE = DC.DEPARTMENT_CODE
WHERE LR.LEAVE_STATUS_CODE = 'APPROVED'
  AND LR.START_DATE + ROWNUM - 1 <= LR.END_DATE
  AND U.STATUS = 'A'
ORDER BY LEAVE_DATE, U.USER_ID;


-- 5. 시퀀스 (Sequences)
-- ========================================

CREATE SEQUENCE SEQ_LEAVE_REQUEST_ID START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ATTENDANCE_RECORD_ID START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LOGIN_ACCOUNT_ID START WITH 1000 INCREMENT BY 1;


-- 6. 샘플 데이터 (Sample Data)
-- ========================================

-- 사용자 샘플 데이터
INSERT INTO TB_USERS (USER_ID, EMPLOYEE_NO, USER_NAME, DEPARTMENT_CODE, POSITION_CODE, EMAIL, TOTAL_LEAVE_DAYS, STATUS)
VALUES ('1', '2020001', '이정호', 'DEV', 'L2', 'jeongho.l@workboard.com', 15, 'A');

INSERT INTO TB_USERS (USER_ID, EMPLOYEE_NO, USER_NAME, DEPARTMENT_CODE, POSITION_CODE, EMAIL, TOTAL_LEAVE_DAYS, STATUS)
VALUES ('2', '2021002', '김민준', 'DEV', 'L2', 'minjun.kim@workboard.com', 15, 'A');

INSERT INTO TB_USERS (USER_ID, EMPLOYEE_NO, USER_NAME, DEPARTMENT_CODE, POSITION_CODE, EMAIL, TOTAL_LEAVE_DAYS, STATUS)
VALUES ('3', '2023003', '이서준', 'DEV', 'L1', 'seojun.lee@workboard.com', 15, 'A');

INSERT INTO TB_USERS (USER_ID, EMPLOYEE_NO, USER_NAME, DEPARTMENT_CODE, POSITION_CODE, EMAIL, TOTAL_LEAVE_DAYS, STATUS)
VALUES ('6', '2018006', '정하준', 'DEV', 'L4', 'hajun.j@workboard.com', 16, 'A');


-- 로그인 계정 샘플 데이터 (패스워드는 SHA256 해싱 필수)
INSERT INTO TB_LOGIN_ACCOUNTS (LOGIN_ACCOUNT_ID, USER_ID, EMAIL, PASSWORD_HASH)
VALUES ('1', '1', 'jeongho.l@workboard.com', 'TODO:HASH_OF_PASSWORD');

INSERT INTO TB_LOGIN_ACCOUNTS (LOGIN_ACCOUNT_ID, USER_ID, EMAIL, PASSWORD_HASH)
VALUES ('6', '6', 'hajun.j@workboard.com', 'TODO:HASH_OF_PASSWORD');


-- 연차 신청 샘플 데이터
INSERT INTO TB_LEAVE_REQUESTS (LEAVE_REQUEST_ID, USER_ID, START_DATE, END_DATE, LEAVE_REASON, LEAVE_STATUS_CODE, CREATED_AT)
VALUES ('1', '1', TO_DATE('2026-04-21', 'YYYY-MM-DD'), TO_DATE('2026-04-21', 'YYYY-MM-DD'), '병원 방문', 'APPROVED', SYSTIMESTAMP);

INSERT INTO TB_LEAVE_REQUESTS (LEAVE_REQUEST_ID, USER_ID, START_DATE, END_DATE, LEAVE_REASON, LEAVE_STATUS_CODE, CREATED_AT)
VALUES ('2', '1', TO_DATE('2026-05-27', 'YYYY-MM-DD'), TO_DATE('2026-05-27', 'YYYY-MM-DD'), '개인 사정', 'APPROVED', SYSTIMESTAMP);


-- ========================================
-- 참고: 마이그레이션 전략
-- ========================================
-- 1. STATUS 컬럼: A(활성), I(비활성), D(삭제) - Soft Delete 구현
-- 2. 타임스탬프: SYSTIMESTAMP 활용 - 데이터 추적성 확보
-- 3. 암호화: PASSWORD_HASH 필드 - 실제 패스워드는 SHA256 또는 bcrypt로 해싱 필수
-- 4. 코드 테이블: 유지보수성과 확장성을 위해 분리
-- 5. 외래키: 참조 무결성 유지
-- 6. 인덱스: 조회 성능 최적화
-- 7. 뷰: 연차 계산 로직을 DB에서 관리 (계산 정확성 보장)
